global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@log-capturer.local'

# Templates para notificações customizadas
templates:
- '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: [ 'alertname', 'cluster', 'service' ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-receiver'
  routes:
  # Rotas específicas por severidade
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 10s
    repeat_interval: 10m
  - match:
      severity: warning
    receiver: 'warning-alerts'
    repeat_interval: 2h

inhibit_rules:
# Inibir alertas de warning quando há critical
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: [ 'alertname', 'cluster', 'service' ]

receivers:
- name: 'default-receiver'
  webhook_configs:
  - url: 'http://localhost:5001/webhook'
    send_resolved: true

- name: 'critical-alerts'
  # Webhook para alerts críticos
  webhook_configs:
  - url: 'http://localhost:5001/webhook/critical'
    send_resolved: true
    # title: 'CRITICAL: Log Capturer Alert'
    # Email para critical (descomente se configurado)
    # email_configs:
    # - to: 'ops-team@company.com'
    #   subject: 'CRITICAL: Log Capturer Alert'
    #   body: |
    #     {{ range .Alerts }}
    #     Alert: {{ .Annotations.summary }}
    #     Description: {{ .Annotations.description }}
    #     {{ end }}

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://localhost:5001/webhook/warning'
    send_resolved: true
    # title: 'WARNING: Log Capturer Alert'
