auth_enabled: false # Desativa autenticação interna do Loki

server:
  http_listen_port: 3100 # Porta HTTP da API/UI
  grpc_listen_port: 9096 # Porta GRPC para comunicação interna

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
  - from: 2024-04-01
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

compactor:
  working_directory: /loki/compactor # Diretório local para compaction (não precisa de shared_store)

limits_config:
  retention_period: 168h # Mantém logs por 7 dias
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_cache_freshness_per_query: 10m
  reject_old_samples_max_age: 168h

query_range:
  align_queries_with_step: true
  parallelise_shardable_queries: true
  cache_results: true

# frontend_worker:
#   frontend_address: 127.0.0.1:9095

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  max_outstanding_per_tenant: 100
