# auth_enabled: false

# server:
#   http_listen_port: 3100

# ingester:
#   lifecycler:
#     address: 127.0.0.1
#     ring:
#       kvstore:
#         store: inmemory
#       replication_factor: 1
#     final_sleep: 0s
#   chunk_idle_period: 5m
#   max_chunk_age: 1h
#   chunk_target_size: 1048576
#   max_transfer_retries: 0

# schema_config:
#   configs:
#     - from: 2020-10-24
#       store: boltdb-shipper
#       object_store: filesystem
#       schema: v11
#       index:
#         prefix: index_
#         period: 24h

# storage_config:
#   boltdb_shipper:
#     active_index_directory: /loki/boltdb-shipper-active
#     cache_location: /loki/boltdb-shipper-cache
#     cache_ttl: 24h
#     shared_store: filesystem
#   filesystem:
#     directory: /loki/chunks

# compactor:
#   working_directory: /loki/compactor
#   shared_store: filesystem

# limits_config:
#   reject_old_samples: true
#   reject_old_samples_max_age: 168h

# chunk_store_config:
#   max_look_back_period: 0s

# table_manager:
#   retention_deletes_enabled: false
#   retention_period: 0s

# auth_enabled: false
# server:
#   http_listen_port: 3100
# ingester:
#   lifecycler:
#     address: 127.0.0.1
#     ring:
#       kvstore:
#         store: inmemory
#       replication_factor: 1
#     final_sleep: 0s
#   # Adicionar configuração do WAL
#   wal:
#     dir: /loki/wal
#   chunk_idle_period: 5m
#   max_chunk_age: 1h
#   chunk_target_size: 1048576
#   max_transfer_retries: 0
# schema_config:
#   configs:
#   - from: 2020-10-24
#     store: boltdb-shipper
#     object_store: filesystem
#     schema: v11
#     index:
#       prefix: index_
#       period: 24h
# storage_config:
#   boltdb_shipper:
#     active_index_directory: /loki/boltdb-shipper-active
#     cache_location: /loki/boltdb-shipper-cache
#     cache_ttl: 24h
#     shared_store: filesystem
#   filesystem:
#     directory: /loki/chunks
# compactor:
#   working_directory: /loki/compactor
#   shared_store: filesystem
# limits_config:
#   reject_old_samples: true
#   reject_old_samples_max_age: 168h
#   volume_enabled: true
# chunk_store_config:
#   max_look_back_period: 0s
# table_manager:
#   retention_deletes_enabled: false
#   retention_period: 0s

auth_enabled: false

server:
  http_listen_port: 3100
  # grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
  - from: 2024-04-01
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

compactor:
  working_directory: /loki/retention
  delete_request_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  retention_period: 120h
  # NOVO: evitar rejeição agressiva de amostras antigas (ajuste conforme necessidade)
  reject_old_samples: true
  reject_old_samples_max_age: 98h

# ruler:
#   alertmanager_url: http://localhost:9093
